wolfsblvt_advancedpolls_infopoll:
    path: /advancedpolls/infopoll/{topic_id}
    defaults: { _controller: wolfsblvt.advancedpolls.controller.infopoll:details }
    requirements:
        topic_id: '\d+'
    methods: [GET]

wolfsblvt_advancedpolls_multi_question_vote:
    path: /advancedpolls/vote/{topic_id}
    defaults: { _controller: wolfsblvt.advancedpolls.controller.multi_question:submit }
    requirements:
        topic_id: '\d+'
    methods: [POST]

wolfsblvt_advancedpolls_poll_list:
    path: /advancedpolls/polls
    defaults: { _controller: wolfsblvt.advancedpolls.controller.poll_list:handle }
    methods: [GET]
