services:
    wolfsblvt.advancedpolls.listener:
        class: wolfsblvt\advancedpolls\event\listener
        arguments:
            - '@wolfsblvt.advancedpolls.advancedpolls'
            - '@wolfsblvt.advancedpolls.vote_user_lifecycle'
            - '@wolfsblvt.advancedpolls.multi_question_manager'
            - '@wolfsblvt.advancedpolls.poll_option_appender'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '@auth'
            - '@path_helper'
            - '@template'
            - '@user'
        tags:
            - {name: event.listener}
    wolfsblvt.advancedpolls.vote_user_lifecycle:
        class: wolfsblvt\advancedpolls\core\vote_user_lifecycle
        arguments:
            - '@dbal.conn'
            - '%core.table_prefix%'
    wolfsblvt.advancedpolls.multi_question_manager:
        class: wolfsblvt\advancedpolls\core\multi_question_manager
        arguments:
            - '@dbal.conn'
            - '%core.table_prefix%'
    wolfsblvt.advancedpolls.poll_option_appender:
        class: wolfsblvt\advancedpolls\core\poll_option_appender
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@notification_manager'
            - '@log'
            - '@user'
            - '@wolfsblvt.advancedpolls.multi_question_manager'
            - '%core.table_prefix%'
    wolfsblvt.advancedpolls.advancedpolls:
        class: wolfsblvt\advancedpolls\core\advancedpolls
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@template'
            - '@user'
            - '@auth'
            - '@request'
            - '@dispatcher'
            - '@controller.helper'

    wolfsblvt.advancedpolls.controller.infopoll:
        class: wolfsblvt\advancedpolls\controller\infopoll
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@request'
    wolfsblvt.advancedpolls.controller.multi_question:
        class: wolfsblvt\advancedpolls\controller\multi_question
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@user'
            - '@request'
            - '@config'
            - '@wolfsblvt.advancedpolls.multi_question_manager'
            - '%core.table_prefix%'
    wolfsblvt.advancedpolls.controller.poll_list:
        class: wolfsblvt\advancedpolls\controller\poll_list
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    wolfsblvt.advancedpolls.notification.type.pollended:
        class: wolfsblvt\advancedpolls\notification\pollended
        shared: false
        parent: notification.type.base
        calls:
            - [set_config, ['@config']]
        tags:
            - {name: notification.type}
    wolfsblvt.advancedpolls.notification.type.optionsadded:
        class: wolfsblvt\advancedpolls\notification\optionsadded
        shared: false
        parent: notification.type.base
        calls:
            - [set_config, ['@config']]
            - [set_table_prefix, ['%core.table_prefix%']]
        tags:
            - {name: notification.type}
    wolfsblvt.advancedpolls.cron.task.pollend:
        class: wolfsblvt\advancedpolls\cron\task\pollend
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@log'
            - '@user'
            - '@notification_manager'
        tags:
            - {name: cron.task}
